language: go

go:
- 1.7
- 1.8

before_install:
- go get -u -v github.com/golang/lint/golint
- go get -u -v golang.org/x/tools/cmd/goimports

install:
- go get ./...

script:
- goimports -l $(find . -type f -name '*.go' ! -path "./proto/*" ! -path "./vendor/*")
- golint -set_exit_status ./...
- go vet ./...
