language: go

go:
- 1.8

before_install:
- go get -u -v github.com/golang/lint/golint
- go get -u -v golang.org/x/tools/cmd/goimports

install:
- go get ./...

script:
- goimports -l $(find . -type f -name '*.go' ! -path "./proto/*" ! -path "./vendor/*")
- test $(goimports -l $(find . -type f -name '*.go' ! -path "./proto/*" ! -path "./vendor/*") | wc -l) -eq 0
- golint -set_exit_status $(go list ./... | grep -v proto | grep -v vendor)
- go vet $(go list ./... | grep -v proto | grep -v vendor)
