// Code generated by protoc-gen-go.
// source: status.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	status.proto
	time-sheet.proto

It has these top-level messages:
	Status
	TimeSheetEntryRef
	TimeSheet
	TimeSheetEntry
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Status_State int32

const (
	Status_STOPPED Status_State = 0
	Status_STARTED Status_State = 1
	Status_PAUSED  Status_State = 2
)

var Status_State_name = map[int32]string{
	0: "STOPPED",
	1: "STARTED",
	2: "PAUSED",
}
var Status_State_value = map[string]int32{
	"STOPPED": 0,
	"STARTED": 1,
	"PAUSED":  2,
}

func (x Status_State) String() string {
	return proto1.EnumName(Status_State_name, int32(x))
}
func (Status_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Status struct {
	State          Status_State       `protobuf:"varint,1,opt,name=state,enum=Status_State" json:"state,omitempty"`
	TimeSheetEntry *TimeSheetEntryRef `protobuf:"bytes,2,opt,name=time_sheet_entry,json=timeSheetEntry" json:"time_sheet_entry,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto1.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Status) GetState() Status_State {
	if m != nil {
		return m.State
	}
	return Status_STOPPED
}

func (m *Status) GetTimeSheetEntry() *TimeSheetEntryRef {
	if m != nil {
		return m.TimeSheetEntry
	}
	return nil
}

type TimeSheetEntryRef struct {
	Date  string `protobuf:"bytes,1,opt,name=date" json:"date,omitempty"`
	Index int64  `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
}

func (m *TimeSheetEntryRef) Reset()                    { *m = TimeSheetEntryRef{} }
func (m *TimeSheetEntryRef) String() string            { return proto1.CompactTextString(m) }
func (*TimeSheetEntryRef) ProtoMessage()               {}
func (*TimeSheetEntryRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TimeSheetEntryRef) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *TimeSheetEntryRef) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto1.RegisterType((*Status)(nil), "Status")
	proto1.RegisterType((*TimeSheetEntryRef)(nil), "TimeSheetEntryRef")
	proto1.RegisterEnum("Status_State", Status_State_name, Status_State_value)
}

func init() { proto1.RegisterFile("status.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x9a, 0xc5, 0xc8, 0xc5, 0x16, 0x0c, 0x16,
	0x10, 0x52, 0xe6, 0x62, 0x05, 0x49, 0xa5, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x19, 0xf1, 0xea,
	0x41, 0xc4, 0xc1, 0x54, 0x6a, 0x10, 0x44, 0x4e, 0xc8, 0x86, 0x4b, 0xa0, 0x24, 0x33, 0x37, 0x35,
	0xbe, 0x38, 0x23, 0x35, 0xb5, 0x24, 0x3e, 0x35, 0xaf, 0xa4, 0xa8, 0x52, 0x82, 0x49, 0x81, 0x51,
	0x83, 0xdb, 0x48, 0x48, 0x2f, 0x24, 0x33, 0x37, 0x35, 0x18, 0x24, 0xee, 0x0a, 0x12, 0x0e, 0x4a,
	0x4d, 0x0b, 0xe2, 0x2b, 0x41, 0x11, 0x52, 0xd2, 0xe5, 0x62, 0x05, 0x9b, 0x26, 0xc4, 0xcd, 0xc5,
	0x1e, 0x1c, 0xe2, 0x1f, 0x10, 0xe0, 0xea, 0x22, 0xc0, 0x00, 0xe1, 0x38, 0x06, 0x85, 0xb8, 0xba,
	0x08, 0x30, 0x0a, 0x71, 0x71, 0xb1, 0x05, 0x38, 0x86, 0x06, 0xbb, 0xba, 0x08, 0x30, 0x29, 0xd9,
	0x72, 0x09, 0x62, 0x98, 0x29, 0x24, 0xc4, 0xc5, 0x92, 0x02, 0x73, 0x25, 0x67, 0x10, 0x98, 0x2d,
	0x24, 0xc2, 0xc5, 0x9a, 0x99, 0x97, 0x92, 0x5a, 0x01, 0x76, 0x0a, 0x73, 0x10, 0x84, 0xe3, 0xc4,
	0x1e, 0xc5, 0x0a, 0xf6, 0x64, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc4,
	0x03, 0x04, 0xaf, 0xfb, 0x00, 0x00, 0x00,
}
