// Code generated by protoc-gen-go.
// source: tracking.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	tracking.proto

It has these top-level messages:
	TrackingStatus
	TrackingTimesheet
	TrackingEntry
	TrackingEntryRef
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// TrackingStatus keeps hold of information about the current "state" of tracking, i.e. whether or
// not a timer is running, and which timer we last modified.
type TrackingStatus struct {
	// Whether or not a (any) timer is running.
	IsRunning bool `protobuf:"varint,1,opt,name=is_running,json=isRunning" json:"is_running,omitempty"`
	// The date of the timesheet currently being tracked.
	Timesheet string `protobuf:"bytes,2,opt,name=timesheet" json:"timesheet,omitempty"`
	// The hash of the entry currently being tracked.
	Entry string `protobuf:"bytes,3,opt,name=entry" json:"entry,omitempty"`
}

func (m *TrackingStatus) Reset()                    { *m = TrackingStatus{} }
func (m *TrackingStatus) String() string            { return proto1.CompactTextString(m) }
func (*TrackingStatus) ProtoMessage()               {}
func (*TrackingStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TrackingStatus) GetIsRunning() bool {
	if m != nil {
		return m.IsRunning
	}
	return false
}

func (m *TrackingStatus) GetTimesheet() string {
	if m != nil {
		return m.Timesheet
	}
	return ""
}

func (m *TrackingStatus) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

// TrackingTimesheet represents a timesheet. It contains all of the entries for a time period.
type TrackingTimesheet struct {
	// The key of this timesheet.
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// A timesheet consists of many entries. A timesheet can be totally empty, it's just there to
	// hold the reference to a bunch of entries under a date, i.e. for easy access.
	Entries []string `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
}

func (m *TrackingTimesheet) Reset()                    { *m = TrackingTimesheet{} }
func (m *TrackingTimesheet) String() string            { return proto1.CompactTextString(m) }
func (*TrackingTimesheet) ProtoMessage()               {}
func (*TrackingTimesheet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TrackingTimesheet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TrackingTimesheet) GetEntries() []string {
	if m != nil {
		return m.Entries
	}
	return nil
}

// TrackingEntry represents an entry in the timesheet. This will have enough information to commit
// to the duration, and also enough information to identify the entry.
type TrackingEntry struct {
	// The key of this entry.
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// The key of the timesheet this entry belongs to.
	Timesheet string `protobuf:"bytes,2,opt,name=timesheet" json:"timesheet,omitempty"`
	// The note associated with this entry.
	Note string `protobuf:"bytes,3,opt,name=note" json:"note,omitempty"`
	// The unix timestamp of when this entry was created.
	Created uint64 `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
	// The unix timestamp of when this entry was last updated.
	Updated uint64 `protobuf:"varint,5,opt,name=updated" json:"updated,omitempty"`
	// The number of seconds this has been tracked for (once committed).
	Duration uint64 `protobuf:"varint,6,opt,name=duration" json:"duration,omitempty"`
}

func (m *TrackingEntry) Reset()                    { *m = TrackingEntry{} }
func (m *TrackingEntry) String() string            { return proto1.CompactTextString(m) }
func (*TrackingEntry) ProtoMessage()               {}
func (*TrackingEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TrackingEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TrackingEntry) GetTimesheet() string {
	if m != nil {
		return m.Timesheet
	}
	return ""
}

func (m *TrackingEntry) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *TrackingEntry) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *TrackingEntry) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *TrackingEntry) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

// TrackingEntryRef represents a reference from an entry's short key to it's full key.
type TrackingEntryRef struct {
	// The key of this entry reference.
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// The key of the entry this reference belongs to.
	Entry string `protobuf:"bytes,2,opt,name=entry" json:"entry,omitempty"`
}

func (m *TrackingEntryRef) Reset()                    { *m = TrackingEntryRef{} }
func (m *TrackingEntryRef) String() string            { return proto1.CompactTextString(m) }
func (*TrackingEntryRef) ProtoMessage()               {}
func (*TrackingEntryRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TrackingEntryRef) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TrackingEntryRef) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

func init() {
	proto1.RegisterType((*TrackingStatus)(nil), "TrackingStatus")
	proto1.RegisterType((*TrackingTimesheet)(nil), "TrackingTimesheet")
	proto1.RegisterType((*TrackingEntry)(nil), "TrackingEntry")
	proto1.RegisterType((*TrackingEntryRef)(nil), "TrackingEntryRef")
}

func init() { proto1.RegisterFile("tracking.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x25, 0xfb, 0xd1, 0x36, 0x03, 0x96, 0x1a, 0x3c, 0x04, 0x51, 0x58, 0xf6, 0xb4, 0x27, 0x2f,
	0xde, 0xbc, 0x08, 0x82, 0x7f, 0x20, 0xf6, 0xe4, 0x45, 0xd6, 0xdd, 0xb1, 0x86, 0x62, 0xb6, 0x24,
	0x93, 0x43, 0x7f, 0x8f, 0x7f, 0x54, 0x92, 0xdd, 0xac, 0x0a, 0xa5, 0xa7, 0xcc, 0x7b, 0x6f, 0x32,
	0xef, 0x31, 0x03, 0x6b, 0xb2, 0x6d, 0xb7, 0xd7, 0x66, 0x77, 0x77, 0xb0, 0x03, 0x0d, 0x75, 0x07,
	0xeb, 0xed, 0xc4, 0xbc, 0x50, 0x4b, 0xde, 0x89, 0x5b, 0x00, 0xed, 0xde, 0xac, 0x37, 0x46, 0x9b,
	0x9d, 0x64, 0x15, 0x6b, 0x56, 0x8a, 0x6b, 0xa7, 0x46, 0x42, 0xdc, 0x00, 0x27, 0xfd, 0x85, 0xee,
	0x13, 0x91, 0x64, 0x56, 0xb1, 0x86, 0xab, 0x5f, 0x42, 0x5c, 0x41, 0x89, 0x86, 0xec, 0x51, 0xe6,
	0x51, 0x19, 0x41, 0xfd, 0x08, 0x97, 0xc9, 0x64, 0x3b, 0xb7, 0x6e, 0x20, 0xdf, 0xe3, 0x31, 0x1a,
	0x70, 0x15, 0x4a, 0x21, 0x61, 0x19, 0xfa, 0x35, 0x3a, 0x99, 0x55, 0x79, 0xc3, 0x55, 0x82, 0xf5,
	0x37, 0x83, 0x8b, 0x34, 0xe1, 0x39, 0x8c, 0x3c, 0xf1, 0xfb, 0x7c, 0x30, 0x01, 0x85, 0x19, 0x08,
	0xa7, 0x5c, 0xb1, 0x0e, 0x7e, 0x9d, 0xc5, 0x96, 0xb0, 0x97, 0x45, 0xc5, 0x9a, 0x42, 0x25, 0x18,
	0x14, 0x7f, 0xe8, 0xa3, 0x52, 0x8e, 0xca, 0x04, 0xc5, 0x35, 0xac, 0x7a, 0x6f, 0x5b, 0xd2, 0x83,
	0x91, 0x8b, 0x28, 0xcd, 0xb8, 0x7e, 0x80, 0xcd, 0xbf, 0x90, 0x0a, 0x3f, 0x4e, 0xe4, 0x9c, 0x57,
	0x94, 0xfd, 0x59, 0xd1, 0xd3, 0xf2, 0xb5, 0x8c, 0x07, 0x79, 0x5f, 0xc4, 0xe7, 0xfe, 0x27, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0x80, 0xe9, 0xce, 0xa9, 0x01, 0x00, 0x00,
}
