// Code generated by protoc-gen-go.
// source: tracking.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	tracking.proto

It has these top-level messages:
	TrackingStatus
	TrackingStatusRef
	TrackingTimesheet
	TrackingEntry
	TrackingEntryRef
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// TrackingState represents all of the different states that tracking can be in.
type TrackingStatus_TrackingState int32

const (
	TrackingStatus_STOPPED TrackingStatus_TrackingState = 0
	TrackingStatus_STARTED TrackingStatus_TrackingState = 1
)

var TrackingStatus_TrackingState_name = map[int32]string{
	0: "STOPPED",
	1: "STARTED",
}
var TrackingStatus_TrackingState_value = map[string]int32{
	"STOPPED": 0,
	"STARTED": 1,
}

func (x TrackingStatus_TrackingState) String() string {
	return proto1.EnumName(TrackingStatus_TrackingState_name, int32(x))
}
func (TrackingStatus_TrackingState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

// TrackingStatus keeps hold of information about the current "state" of tracking, i.e. whether or
// not a timer is running, and which timer we last modified.
type TrackingStatus struct {
	// The current tracking state.
	State TrackingStatus_TrackingState `protobuf:"varint,1,opt,name=state,enum=TrackingStatus_TrackingState" json:"state,omitempty"`
	// The current reference to a timesheet and entry.
	Ref *TrackingStatusRef `protobuf:"bytes,2,opt,name=ref" json:"ref,omitempty"`
}

func (m *TrackingStatus) Reset()                    { *m = TrackingStatus{} }
func (m *TrackingStatus) String() string            { return proto1.CompactTextString(m) }
func (*TrackingStatus) ProtoMessage()               {}
func (*TrackingStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TrackingStatus) GetState() TrackingStatus_TrackingState {
	if m != nil {
		return m.State
	}
	return TrackingStatus_STOPPED
}

func (m *TrackingStatus) GetRef() *TrackingStatusRef {
	if m != nil {
		return m.Ref
	}
	return nil
}

// TrackingStatusRef represents a reference to a timesheet and an entry. This is used to find
// the data to perform updates, etc.
type TrackingStatusRef struct {
	// Timesheet references the date of the timesheet. This corresponds to the key the timesheet
	// is stored under in the database.
	Timesheet string `protobuf:"bytes,1,opt,name=timesheet" json:"timesheet,omitempty"`
	// Entry references the hash of the entry itself. Similar to a Git commit hash.
	Entry string `protobuf:"bytes,2,opt,name=entry" json:"entry,omitempty"`
}

func (m *TrackingStatusRef) Reset()                    { *m = TrackingStatusRef{} }
func (m *TrackingStatusRef) String() string            { return proto1.CompactTextString(m) }
func (*TrackingStatusRef) ProtoMessage()               {}
func (*TrackingStatusRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TrackingStatusRef) GetTimesheet() string {
	if m != nil {
		return m.Timesheet
	}
	return ""
}

func (m *TrackingStatusRef) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

// TrackingTimesheet represents a timesheet. It contains all of the entries for a time period.
type TrackingTimesheet struct {
	// The key of this timesheet.
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// A timesheet consists of many entries. A timesheet can be totally empty, it's just there to
	// hold the reference to a bunch of entries under a date, i.e. for easy access.
	Entries []string `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
}

func (m *TrackingTimesheet) Reset()                    { *m = TrackingTimesheet{} }
func (m *TrackingTimesheet) String() string            { return proto1.CompactTextString(m) }
func (*TrackingTimesheet) ProtoMessage()               {}
func (*TrackingTimesheet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TrackingTimesheet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TrackingTimesheet) GetEntries() []string {
	if m != nil {
		return m.Entries
	}
	return nil
}

// TrackingEntry represents an entry in the timesheet. This will have enough information to commit
// to the duration, and also enough information to identify the entry.
type TrackingEntry struct {
	// The key of this entry.
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// The key of the timesheet this entry belongs to.
	Timesheet string `protobuf:"bytes,2,opt,name=timesheet" json:"timesheet,omitempty"`
	// The note associated with this entry.
	Note string `protobuf:"bytes,3,opt,name=note" json:"note,omitempty"`
	// The unix timestamp of when this entry was created.
	Created uint64 `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
	// The unix timestamp of when this entry was last updated.
	Updated uint64 `protobuf:"varint,5,opt,name=updated" json:"updated,omitempty"`
	// The number of seconds this has been tracked for (once committed).
	Duration uint64 `protobuf:"varint,6,opt,name=duration" json:"duration,omitempty"`
}

func (m *TrackingEntry) Reset()                    { *m = TrackingEntry{} }
func (m *TrackingEntry) String() string            { return proto1.CompactTextString(m) }
func (*TrackingEntry) ProtoMessage()               {}
func (*TrackingEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TrackingEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TrackingEntry) GetTimesheet() string {
	if m != nil {
		return m.Timesheet
	}
	return ""
}

func (m *TrackingEntry) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *TrackingEntry) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *TrackingEntry) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *TrackingEntry) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

// TrackingEntryRef represents a reference from an entry's short key to it's full key.
type TrackingEntryRef struct {
	// The key of this entry reference.
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// The key of the entry this reference belongs to.
	Entry string `protobuf:"bytes,2,opt,name=entry" json:"entry,omitempty"`
}

func (m *TrackingEntryRef) Reset()                    { *m = TrackingEntryRef{} }
func (m *TrackingEntryRef) String() string            { return proto1.CompactTextString(m) }
func (*TrackingEntryRef) ProtoMessage()               {}
func (*TrackingEntryRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TrackingEntryRef) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TrackingEntryRef) GetEntry() string {
	if m != nil {
		return m.Entry
	}
	return ""
}

func init() {
	proto1.RegisterType((*TrackingStatus)(nil), "TrackingStatus")
	proto1.RegisterType((*TrackingStatusRef)(nil), "TrackingStatusRef")
	proto1.RegisterType((*TrackingTimesheet)(nil), "TrackingTimesheet")
	proto1.RegisterType((*TrackingEntry)(nil), "TrackingEntry")
	proto1.RegisterType((*TrackingEntryRef)(nil), "TrackingEntryRef")
	proto1.RegisterEnum("TrackingStatus_TrackingState", TrackingStatus_TrackingState_name, TrackingStatus_TrackingState_value)
}

func init() { proto1.RegisterFile("tracking.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x5d, 0x4a, 0xc1, 0x0e, 0x91, 0xd4, 0x8d, 0x87, 0x8d, 0xd1, 0xa4, 0xd9, 0x78, 0xa8,
	0x17, 0x0e, 0x70, 0xf3, 0x62, 0x34, 0x34, 0x1e, 0x25, 0x4b, 0x4f, 0xde, 0x2a, 0x1d, 0xb4, 0x21,
	0xb6, 0x64, 0x3b, 0x3d, 0xf0, 0x22, 0xbe, 0x80, 0x2f, 0x6a, 0x76, 0x5b, 0x68, 0x0a, 0x9c, 0x3a,
	0xff, 0xfc, 0x33, 0x7f, 0xbf, 0x4c, 0x16, 0xc6, 0xa4, 0x93, 0xd5, 0x26, 0xcb, 0xbf, 0x26, 0x5b,
	0x5d, 0x50, 0x21, 0x7f, 0x19, 0x8c, 0xe3, 0xa6, 0xb5, 0xa4, 0x84, 0xaa, 0x92, 0xcf, 0xc0, 0x2d,
	0x29, 0x21, 0x14, 0x2c, 0x60, 0xe1, 0x78, 0x7a, 0x3f, 0xe9, 0xfa, 0x1d, 0x89, 0xaa, 0x9e, 0xe5,
	0x0f, 0xe0, 0x68, 0x5c, 0x8b, 0x5e, 0xc0, 0xc2, 0xd1, 0x94, 0x1f, 0xad, 0x28, 0x5c, 0x2b, 0x63,
	0xcb, 0x47, 0xb8, 0xea, 0x6c, 0xf3, 0x11, 0x0c, 0x97, 0xf1, 0xfb, 0x62, 0x11, 0xcd, 0xfd, 0x8b,
	0x5a, 0xbc, 0xa8, 0x38, 0x9a, 0xfb, 0x4c, 0xbe, 0xc1, 0xf5, 0x49, 0x08, 0xbf, 0x03, 0x8f, 0xb2,
	0x1f, 0x2c, 0xbf, 0x11, 0xc9, 0xe2, 0x79, 0xaa, 0x6d, 0xf0, 0x1b, 0x70, 0x31, 0x27, 0xbd, 0xb3,
	0x14, 0x9e, 0xaa, 0x85, 0x7c, 0x6e, 0x83, 0xe2, 0xc3, 0xa8, 0x0f, 0xce, 0x06, 0x77, 0x4d, 0x84,
	0x29, 0xb9, 0x80, 0xa1, 0x99, 0xcf, 0xb0, 0x14, 0xbd, 0xc0, 0x09, 0x3d, 0xb5, 0x97, 0xf2, 0x8f,
	0xb5, 0xd4, 0x91, 0x89, 0x3c, 0xb3, 0xdd, 0x01, 0xeb, 0x1d, 0x83, 0x71, 0xe8, 0xe7, 0x05, 0xa1,
	0x70, 0xac, 0x61, 0x6b, 0xf3, 0xbf, 0x95, 0xc6, 0x84, 0x30, 0x15, 0xfd, 0x80, 0x85, 0x7d, 0xb5,
	0x97, 0xc6, 0xa9, 0xb6, 0xa9, 0x75, 0xdc, 0xda, 0x69, 0x24, 0xbf, 0x85, 0xcb, 0xb4, 0xd2, 0x09,
	0x65, 0x45, 0x2e, 0x06, 0xd6, 0x3a, 0x68, 0xf9, 0x04, 0x7e, 0x07, 0xd2, 0x9c, 0xeb, 0x94, 0xf3,
	0xec, 0x89, 0x5e, 0x87, 0x1f, 0xae, 0x7d, 0x0d, 0x9f, 0x03, 0xfb, 0x99, 0xfd, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x5c, 0xfb, 0xd1, 0x29, 0x26, 0x02, 0x00, 0x00,
}
